### ISSUE TITLE
Error using React 18

### ISSUE THREAD

**Issue by jereef** [Mimetis/msal-react-tester#1]
![error-react](https://user-images.githubusercontent.com/6531964/181037062-ef0b86db-8756-4cad-9c16-7ea282e7ea15.jpg)

It seems to me that it is not compatible with react 18, I am using testing-library in version 13.
I tried downgrading to 12.1.5 but it is not compatible with my version of react.

**Comment by Mimetis** [comment]
Thanks @jereef for the feedback
Will push asap a new updated version !

**Comment by Mimetis** [comment]
hey @jereef.
Just published a new version (`0.1.2`) that should work with the last version of `react`.

Let me know if it's working for you using this new package.

**Comment by jereef** [comment]
Great! works perfect, thanks!!, great job on this library😁
