### ISSUE TITLE
Initial login credentials seem to be cached

### ISSUE THREAD

**Issue by aihrig** [Mimetis/msal-react-tester#10]
@Mimetis This library is a great time saver, thank you!

I'm currently trying to set up a basic test to render the page when logged out, and verify there is a "sign-in" prompt, but it seems that after the first waitForRedirect() the app is already logged in.

Basic code from example:

```javascript
describe('Authentication', () => {
  beforeEach(() => {
    msalTester = new MsalReactTester('Redirect');

    // Ask msal-react-tester to handle and mock all msal-react processes:
    msalTester.spyMsal();
  });

  afterEach(() => {
    // reset msal-react-tester
    msalTester.resetSpyMsal();
  });

  test.only('Page renders correctly when not signed in', async () => {
    msalTester.isNotLogged();
    render(
      <MsalProvider instance={msalTester.client}>
        <MemoryRouter>
          <App />
        </MemoryRouter>
      </MsalProvider>
    );

    await msalTester.waitForRedirect();
    screen.debug(); // <--- Displays authenticated page contents instead of MS Sign-in page
    expect(screen.getByText(/Please login/)).toBeInTheDocument();
  });
```

The expect fails because at this point the app is logged in and rendered the authenticated page.

Am I missing something on possibly clearing out cached credentials or something?

Thank you!

**Comment by Mimetis** [comment]
Well, your code seems pretty legit from what I see here.

You are doing the same kind of code as we have here:

https://github.com/Mimetis/msal-react-tester/blob/1b13d366bb5c9fa509159c7eb35f88449e257fe6/create-react-app-sample/src/pages/HomePage.test.tsx#L26-L41

The only different thing I see here is the use of `test.only()` but I don't think it could be the issue honestly...

**Comment by aihrig** [comment]
Yeah, I've tried removing only, just having that as the only test. And what's also frustrating is that every once and a while, it will actually show the sign-in page, maybe 1 out of 100 reloads.

**Comment by Mimetis** [comment]
Can you share a github repository sample (really simple if possible) where you are able to reproduce the bug ?
I will look into it ?
