### ISSUE TITLE
API changes in @azure/msal-browser v2.32

### ISSUE THREAD

**Issue by frankieali** [Mimetis/msal-react-tester#11]
I was hopeful this project would get me around authentication for development, but it seems the api has changed quite a bit in `"@azure/msal-browser": "^2.32.2"` and `"@azure/msal-react": "^1.5.2"`. Do you have any plans to update this project to match the latest from msal?
If nothing else, this project is a great template on what needs to be done to mock the msal provider. Thanks for that.

**Comment by Mimetis** [comment]
Yes, I will update the package to the last version
Thanks for the feedback @frankieali !

**Comment by Mimetis** [comment]
Should be resolved now with last version
