### ISSUE TITLE
Jest encountered an unexpected token error

### ISSUE THREAD

**Issue by bertilvdk** [Mimetis/msal-react-tester#19]
When I try to run a test using MsalReactTester, I get the following error:

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when 
    Jest is not configured to support such syntax.
    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /<path_to_project>/<project>/node_modules/msal-react-tester/dist/index.js:3
    export { default as MsalReactTester } from './MsalReactTester.js';
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      11 | import { MsalProvider } from '@azure/msal-react'
      12 | import { fireEvent, render, screen } from '@testing-library/react'
    > 13 | import { MsalReactTester } from 'msal-react-tester'
         | ^
      14 |
      15 | const { getByTestId, getAllByTestId } = screen
      16 |

Test setup:

```
let msalTester: MsalReactTester

beforeEach(async () => {
    msalTester = new MsalReactTester()
    msalTester.spyMsal()
})

afterEach(() => {
    jest.restoreAllMocks()
    msalTester.resetSpyMsal()
})

function LoginComponent() {
    return (
        <MsalProvider instance={msalTester.client}>
            <MemoryRouter initialEntries={['/login']}>
                <TestDataProvider>
                    <TestUIProvider>
                        <TestUserProvider>
                            <Login />
                        </TestUserProvider>
                    </TestUIProvider>
                </TestDataProvider>
            </MemoryRouter>
        </MsalProvider>
    )
}

describe('Login component', () => {
    it('renders login form when no user in local storage', async () => {
        render(<LoginComponent />)
        expect(getByTestId('login-form')).toBeInTheDocument()
    })
})
```

**Comment by Mimetis** [comment]
Are you using `vitest` or `create-react-app` ?
because `create-react-app` is not working at the time.

**Comment by bertilvdk** [comment]
I'm using `create-react-app` indeed.

Any idea when it will be fixed and if an earlier version would solve the issue for now?

**Comment by Mimetis** [comment]
you need to use a previous version from `msal-react` if i remember well, or use `vitest`

**Comment by Mimetis** [comment]
Did you find a solution ?

**Comment by bertilvdk** [comment]
Nope, but closed the issue as it looks like it's more of an issue on the msal package than this one.

**Comment by Mimetis** [comment]
I'm sorry about that, I tried to resolve the issue, but seems I was not able to make it work with `create-react-app`

If you can use a version of `msal-react` < **2.0.0** (and maybe a previous version of `msal-react-tester`) it should work

**Comment by bertilvdk** [comment]
Will try that, where can I find a list of all the released versions?

**Comment by Mimetis** [comment]
https://www.npmjs.com/package/msal-react-tester?activeTab=versions

Make a test with msal-react-tester 0.2.2 and msal-react >= 1.5.4 or < 2.0.0

**Comment by bertilvdk** [comment]
That did the trick, thanks!
