### ISSUE TITLE
Conflict with MSW mocking?

### ISSUE THREAD

**Issue by JeffreyStevens** [Mimetis/msal-react-tester#3]
Finally I am able to mock an authenticated user, thank you for that! I tried going to my landing page for an authenticated user which automatically does a few API calls. The API calls are mocked using MSW but the mocks are being ignored. I suspect there is a conflict with msal-react-tester mocking? My test case is successful but because my server mocks fail my landing page isn't shown.

My test case:

    test('finds sidebar item for logged in user john doe', async () => {
        const user = userEvent.setup();

        // MSW is not finding my server mocks...
        server.use(
            rest.get('/users', (req, res, ctx) => {
                // console.log('users:');
                return res(ctx.status(200), ctx.json(getMockQueryResult([mockJohnDoeUser])));
            }),
            rest.get('/locations', (req, res, ctx) => {
                // console.log('locations:');
                return res(ctx.status(200), ctx.json(getMockQueryResult(mockLocations)));
            }),
            rest.get('/sort-groups', (req, res, ctx) => {
                // console.log('sort-groups:');
                return res(ctx.status(200), ctx.json(getMockQueryResult(mockSortGroups)));
            }),
            rest.get('/sort-group-work-lists', (req, res, ctx) => {
                // console.log('sort-group-work-lists:');
                return res(ctx.status(200), ctx.json(getMockQueryResult(mockSortGroupWorkLists)));
            }),
        );

        // mock logged in user john doe
        msalTester.isLogged();
        msalTester.accounts[0] = mockMsalAccount; // add idTokenClaims with roles[] array
        renderComponent();

        // wait for msal-react-tester to handle events from msal-react:
        await msalTester.waitForRedirect();

        // verify page content for default route
        expect(await screen.getByText(/buildings/i)).toBeInTheDocument();
    });

And the error:

    console.warn
    [MSW] Warning: captured a request without a matching request handler:
    
      • GET https://mcl-dev-stsapi.mayo.edu/api/locations
    
    If you still wish to intercept this unhandled request, please create a request handler for it.
    Read more: https://mswjs.io/docs/getting-started/mocks

      at Object.warn (node_modules/msw/src/utils/internal/devUtils.ts:17:11)
      at applyStrategy (node_modules/msw/src/utils/request/onUnhandledRequest.ts:208:18)
      at onUnhandledRequest (node_modules/msw/src/utils/request/onUnhandledRequest.ts:233:3)
      at handleRequest (node_modules/msw/src/utils/handleRequest.ts:80:5)
      at setupServerListener (node_modules/msw/src/node/createSetupServer.ts:75:24)

**Comment by Mimetis** [comment]
Hard to debug here...;
Are you able to create a small sample repository, that reproduce the error ?

**Comment by JeffreyStevens** [comment]
I’ll work on it tomorrow for you. Thanks for responding!

**Comment by JeffreyStevens** [comment]
Let me know if this works: [JeffreyStevens/cra-msal-tester](https://github.com/JeffreyStevens/cra-msal-tester)

**Comment by Mimetis** [comment]
thanks, I'm currently in vacation, but will look into it next week

**Comment by Mimetis** [comment]
hey @JeffreyStevens 
I took some time to look into your issue.

You have two different issues eventually:

**First**, you need to wait until you have a response from your call to your local web api.
You have an error raised because the check on the `/API Status: Success/i` is done _**before**_ the result of the call to you api.

You can try something like `await new Promise((r) => setTimeout(r, 10));` but you will have a **Second** error about updating a state without using `act(() => )`

I've already encountered that kind of issue and the trick is to create a short function to emulate a wait time inside an `act()` call:

``` ts
const actAwait = async (interval: number): Promise<void> => {
    let awaiter = (interval: number): Promise<void> => new Promise((r, s) => setTimeout(r, interval));
    return act(async () => await awaiter(interval));
```

Oh, last thing, I had to replace the `/users` with `https://localhost.mayo.edu/api/users/` in the api mock...
Not sure it's mandatory, but it didn't work with just `/users`... You are probably better than me to see what's going on here...

The final result I have is:

``` ts
test('finds landing page for logged in user', async () => {

    server.use(
        rest.get('https://localhost.mayo.edu/api/users/', (req, res, ctx) => {
            console.log('users:');
            return res(ctx.status(200), ctx.json(getMockQueryResult(mockUsers)));
        }),
    );

    // mock logged in user
    msalTester.isLogged();
    msalTester.accounts[0] = mockMsalAccount; // add idTokenClaims with roles[] array
    renderComponent();

    // wait for msal-react-tester to handle events from msal-react:
    await msalTester.waitForRedirect();

    // verify page content for default route
    expect(await screen.getByText(/Authenticated Component/i)).toBeInTheDocument();

    await actAwait(10);

    // the following check works now
    expect(await screen.getByText(/API Status: Success/i)).toBeInTheDocument();
});
```
And it should work as expected !

![image](https://user-images.githubusercontent.com/4592555/200296695-76503ed1-10a5-4de5-a38d-c1c5ac769b8c.png)

Let me know

**Comment by JeffreyStevens** [comment]
Thank you! I will check it out and let you know if I find anything interesting.

**Comment by JeffreyStevens** [comment]
So it turns out I haven't written many top level component tests due to the authentication issue. Now that authentication is working, the `<RequestInterceptor  />` component is actually being invoked when I test a top-level component such as `<Router />` and it calls the following line, which alters the back-end API axios URI needed (meaning I need to mock the full back-end URI prefix):

        // The resource_url is environment dependent.
        const resource_url = getResourceUrl();

Children components when tested do not call `<RequestInterceptor  />` and therefore worked with `/users` and not `https://localhost.mayo.edu/api/users/` in the api mock...

I also made the mistake of not using a 'findBy' query here instead of the 'getBy' query but it turns out I still need the actAwait to allow all the useState calls to resolve and not have a bunch of console errors.

Thanks for helping troubleshoot! I'm a bit excited knowing I can test the top-level stuff now!!

**Comment by Mimetis** [comment]
Enjoy testing stuff ;)
