### ISSUE TITLE
Can we run a test with a user details for authentication

### ISSUE THREAD

**Issue by gauravr7** [Mimetis/msal-react-tester#4]
Hi,
Is there a way to test for the logged in user details.

I have some functionality that requires testing for username and email of the logged in user.

I was using ADAL earlier in which it was fairly simple to test it.

**Comment by Mimetis** [comment]
Basically, you can output these values in the web ui, and tests if they are existing ?

**Comment by gauravr7** [comment]
Can you please share the link for the documentation, where I can access the logged in user.

**Comment by Mimetis** [comment]
https://github.com/Mimetis/msal-react-tester/blob/1b13d366bb5c9fa509159c7eb35f88449e257fe6/create-react-app-sample/src/pages/HomePage.test.tsx#L43-L61

**Comment by gauravr7** [comment]
Thanks @Mimetis
