### ISSUE TITLE
Azure Testing App Roles

### ISSUE THREAD

**Issue by jritchie02** [Mimetis/msal-react-tester#5]
Hello, with my App config I have also added App roles which return as an array under the IdTokenClaims["roles"] = ["Admin"] for example. UI components are passed into a wrapper class, and will only render the children components if the users has the correct role in their IdTokenClaims list. Is there any way to configure the "fake" users roles with this package? If not, what is the best way to handle testing role based access control inside of the msal package? Thanks for any advice!

**Comment by Mimetis** [comment]
You can use the `MsalReactTester` ctor:


``` py
let msalTester: MsalReactTester;

beforeEach(() => {
  let testAccountInfo: AccountInfo = {
    homeAccountId: "home-account-id",
    localAccountId: "local-account-id",
    environment: 'login.windows.net',
    tenantId: "tenant-id",
    username: 'john.doe@contoso.com',
    name: 'John Doe',
  };

  let authenticationResult: AuthenticationResult = {
    authority: 'https://login.microsoftonline.com',
    uniqueId: 'unique-id',
    tenantId: 'tenant-id',
    scopes: ['openid', 'profile'],
    idToken: TEST_ID_TOKEN,
    idTokenClaims: {},
    accessToken: TEST_ACCESS_TOKEN,
    fromCache: false,
    correlationId: 'test-correlation-id',
    expiresOn: new Date(Date.now() + 3600000),
    account: defaultTestAccountInfo,
    tokenType: 'Bearer',
  };
  // new instance of msal tester for each test
  msalTester = new MsalReactTester("Redirect", testAccountInfo, authenticationResult);
  // spy all required msal things
  msalTester.spyMsal();
});


```

**Comment by jritchie02** [comment]
I have tried the following 

`export const defaultTestAccountInfo = {
    homeAccountId: "home-account-id",
    localAccountId: "local-account-id",
    environment: 'login.windows.net',
    tenantId: "tenant-id",
    username: 'knock.tester@contoso.com',
    name: 'Knock teser',
};

beforeEach(() => {
    let testAccountInfo = {
        homeAccountId: "home-account-id",
        localAccountId: "local-account-id",
        environment: 'login.windows.net',
        tenantId: "tenant-id",
        username: 'knock.tester@contoso.com',
        name: 'Knock tester',
    };

    let authenticationResult = {
        authority: 'https://login.microsoftonline.com',
        uniqueId: 'unique-id',
        tenantId: 'tenant-id',
        scopes: ['openid', 'profile'],
        idToken: 'test-id-token',
        idTokenClaims: {roles : ["Admin"]},
        accessToken: TEST_ACCESS_TOKEN,
        fromCache: false,
        correlationId: 'test-correlation-id',
        expiresOn: new Date(Date.now() + 3600000),
        account: defaultTestAccountInfo,
        tokenType: 'Bearer',
    };
    // new instance of msal tester for each test
    msalTester = new MsalReactTester("Redirect", testAccountInfo, authenticationResult);
    // spy all required msal things
    msalTester.spyMsal();
});
`

Inside my wrapper class, I can access
 `const currentAccount = instance.getActiveAccount();
  console.log("The tenantID is " + currentAccount.name)
  console.log("The id Token claims " + currentAccount.idTokenClaims);
`

Where the currentAccount.name prints Knock tester, but the currentAccount.idTokenClaims only outputs undefined? Am I missing something here?

**Comment by jritchie02** [comment]
Looks like I was missing the idTokenClaims in the defaultTestAccountInfo

`
export const defaultTestAccountInfo = {
    homeAccountId: "home-account-id",
    localAccountId: "local-account-id",
    environment: 'login.windows.net',
    tenantId: "tenant-id",
    username: 'knock.tester@contoso.com',
    name: 'Knock tester',
    idTokenClaims: {
        roles: ["Admin"]
    }
};

beforeEach(() => {
    let testAccountInfo = {
        homeAccountId: "home-account-id",
        localAccountId: "local-account-id",
        environment: 'login.windows.net',
        tenantId: "tenant-id",
        username: 'knock.tester@contoso.com',
        name: 'Knock tester',
        idTokenClaims: {
            roles: ["Admin"]
        }
    };
`

It is working as expected, thanks for your help!!
